version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - NEO4J_HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password

  neo4j:
    image: neo4j:4.1
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - db:/data

volumes:
  db:
